make tests against content good

diff --git a/.github/workflows/test-content.yml b/.github/workflows/test-content.yml
--- a/.github/workflows/test-content.yml
+++ b/.github/workflows/test-content.yml
@@ -1,5 +1,9 @@
 name: Test content master against engine
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 on:
   push:
     branches: [master]
@@ -8,46 +12,244 @@ on:
 
 jobs:
   build:
+    if: github.event.pull_request.draft == false
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check out content
-        uses: actions/checkout@v4.2.2
-        with:
-          repository: Trauma-Station/Trauma-Station
-          submodules: recursive
+    - name: Check out content
+      uses: actions/checkout@v4.2.2
+      with:
+        repository: Trauma-Station/Trauma-Station
+        submodules: recursive
+    - name: Disable submodule autoupdate
+      run: touch BuildChecker/DISABLE_SUBMODULE_AUTOUPDATE
+    - name: Check out engine version
+      run: |
+        cd RobustToolbox
+        git fetch origin ${{ github.sha }}
+        git checkout FETCH_HEAD
+        git submodule update --init --recursive
+    - name: Replace global.json
+      run: cp RobustToolbox/global.json .
 
-      - name: Setup .NET Core
-        uses: actions/setup-dotnet@v4.1.0
-        with:
-          dotnet-version: 10.0.x
-      - name: Disable submodule autoupdate
-        run: touch BuildChecker/DISABLE_SUBMODULE_AUTOUPDATE
+    - name: Setup .NET Core
+      uses: actions/setup-dotnet@v4.1.0
+      with:
+        dotnet-version: 10.0.x
 
-      - name: Check out engine version
+    - name: Install dependencies
+      run: dotnet restore
+
+    - name: Build Project
+      run: dotnet build --configuration DebugOpt --no-restore /m
+
+    - name: Save build artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: build-output
+        path: |
+          bin/Content.*/*.json
+          bin/Content.IntegrationTests/*.dll
+          bin/Content.IntegrationTests/*.pdb
+          bin/Content.IntegrationTests/runtimes/linux-x64/**
+          bin/Content.MapRenderer/*.dll
+          bin/Content.MapRenderer/*.pdb
+          bin/Content.Tests/*.dll
+        retention-days: 1
+
+  # Run Content.Tests unit tests separately, nothing depends on them so it's quick (~2 mins total)
+  test-unit:
+    needs: build
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check out content
+      uses: actions/checkout@v4.2.2
+      with:
+        repository: Trauma-Station/Trauma-Station
+        submodules: recursive
+    - name: Disable submodule autoupdate
+      run: touch BuildChecker/DISABLE_SUBMODULE_AUTOUPDATE
+    - name: Check out engine version
+      run: |
+        cd RobustToolbox
+        git fetch origin ${{ github.sha }}
+        git checkout FETCH_HEAD
+        git submodule update --init --recursive
+    - name: Replace global.json
+      run: cp RobustToolbox/global.json .
+
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v4.1.0
+      with:
+        dotnet-version: 10.0.x
+
+    - name: Download build artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: build-output
+        path: bin/
+
+    - name: Link runtimes
+      run: ln -s $(pwd)/bin/Content.IntegrationTests/runtimes bin/Content.Tests/
+
+    - name: Run Content.Tests
+      run: dotnet test bin/Content.Tests/Content.Tests.dll -- NUnit.ConsoleOut=0 NUnit.TestOutputXml="logs" NUnit.WorkDirectory="$(pwd)/test_results"
+
+    # never seen it fail once IDC about archiving it
+
+  # Run every test except map loading tests, they take a little while
+  # Any test with Category("MapTests") is excluded
+  test-main:
+    needs: build
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check out content
+      uses: actions/checkout@v4.2.2
+      with:
+        repository: Trauma-Station/Trauma-Station
+        submodules: recursive
+    - name: Disable submodule autoupdate
+      run: touch BuildChecker/DISABLE_SUBMODULE_AUTOUPDATE
+    - name: Check out engine version
+      run: |
+        cd RobustToolbox
+        git fetch origin ${{ github.sha }}
+        git checkout FETCH_HEAD
+        git submodule update --init --recursive
+    - name: Replace global.json
+      run: cp RobustToolbox/global.json .
+
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v4.1.0
+      with:
+        dotnet-version: 10.0.x
+
+    - name: Download build artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: build-output
+        path: bin/
+
+    - name: Run main Content.IntegrationTests
+      run: |
+        DOTNET_gcServer=1 dotnet test bin/Content.IntegrationTests/Content.IntegrationTests.dll -- \
+          NUnit.Where="cat != MapTests" \
+          NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed NUnit.TestOutputXml="logs" NUnit.WorkDirectory="$(pwd)/test_results"
+
+    - name: Archive NUnit3 test results
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: nunit3-results-main-${{ github.run_attempt }}
+        path: test_results/*
+        retention-days: 7
+        compression-level: 9
+
+  # Test all the map tests seperately
+  # Any test with Category("MapTests") is used
+  test-maps:
+    needs: build
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out content
+      uses: actions/checkout@v4.2.2
+      with:
+        repository: Trauma-Station/Trauma-Station
+        submodules: recursive
+    - name: Disable submodule autoupdate
+      run: touch BuildChecker/DISABLE_SUBMODULE_AUTOUPDATE
+    - name: Check out engine version
+      run: |
+        cd RobustToolbox
+        git fetch origin ${{ github.sha }}
+        git checkout FETCH_HEAD
+        git submodule update --init --recursive
+    - name: Replace global.json
+      run: cp RobustToolbox/global.json .
+
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v4.1.0
+      with:
+        dotnet-version: 10.0.x
+
+    - name: Download build artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: build-output
+        path: bin/
+
+    - name: Run MapTests
+      run: |
+        DOTNET_gcServer=1 dotnet test bin/Content.IntegrationTests/Content.IntegrationTests.dll -- \
+          NUnit.Where="cat == MapTests" \
+          NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed NUnit.TestOutputXml="logs" NUnit.WorkDirectory="$(pwd)/test_results"
+
+    - name: Archive NUnit3 test results
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: nunit3-results-maps-${{ github.run_attempt }}
+        path: test_results/*
+        retention-days: 7
+        compression-level: 9
+
+  test-map-render:
+    needs: build
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out content
+      uses: actions/checkout@v4.2.2
+      with:
+        repository: Trauma-Station/Trauma-Station
+        submodules: recursive
+    - name: Disable submodule autoupdate
+      run: touch BuildChecker/DISABLE_SUBMODULE_AUTOUPDATE
+    - name: Check out engine version
+      run: |
+        cd RobustToolbox
+        git fetch origin ${{ github.sha }}
+        git checkout FETCH_HEAD
+        git submodule update --init --recursive
+    - name: Replace global.json
+      run: cp RobustToolbox/global.json .
+
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v4.1.0
+      with:
+        dotnet-version: 10.0.x
+
+    - name: Download build artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: build-output
+        path: bin/
+
+    - name: Link runtimes
+      run: ln -s $(pwd)/bin/Content.IntegrationTests/runtimes bin/Content.MapRenderer/
+
+    - name: Run Map Renderer
+      run: dotnet exec bin/Content.MapRenderer/Content.MapRenderer.dll Dev
+
+  ci-success:
+    name: Build & Test Debug
+    needs: [build, test-unit, test-main, test-maps, test-map-render]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: CI succeeded
         run: |
-          cd RobustToolbox
-          git fetch origin ${{ github.sha }}
-          git checkout FETCH_HEAD
-          git submodule update --init --recursive
-      - name: Replace global.json
-        run: cp RobustToolbox/global.json .
-      - name: Install dependencies
-        run: dotnet restore
-      - name: Build
-        run: dotnet build --configuration DebugOpt --no-restore /m
-      - name: Content.Tests
-        shell: pwsh
-        run: dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0 NUnit.TestOutputXml="$(pwd)/test_results"
-      - name: Content.IntegrationTests
-        shell: pwsh
-        run: |
-          $env:DOTNET_gcServer=1
-          dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed NUnit.TestOutputXml="logs" NUnit.WorkDirectory="$(pwd)/test_results"
-      - name: Archive NUnit3 test results.
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: nunit3-results
-          path: test_results/*
-          retention-days: 7
+          if [[ "${{ needs.build.result }}" != "success" ||
+                "${{ needs.test-unit.result }}" != "success" ||
+                "${{ needs.test-main.result }}" != "success" ||
+                "${{ needs.test-maps.result }}" != "success" ||
+                "${{ needs.test-map-render.result }}" != "success" ]]; then
+            echo "Not all tests succeeded!"
+            exit 1
+          fi
+          exit 0
